cleanups to merge-sync-tags

diff --git a/bin/merge-sync-tags b/bin/merge-sync-tags
--- a/bin/merge-sync-tags
+++ b/bin/merge-sync-tags
@@ -18,38 +18,41 @@ while [ "$KA_ROOT" != "/" ] && ! [ -f "$KA_ROOT/.ka_root" ]; do
     KA_ROOT="$(dirname "$PWD")"
 done
 
+if [ "$#" -gt 0 ]; then
+    files=("$@")
+else
+    files=()
+    while read -r -d ''; do
+        files+=("$REPLY")
+    done < <(git diff -z --name-only --diff-filter=U)
+fi
+
+# TODO: use ancesdir instead, to avoid needing ka-root?
 if [ "$KA_ROOT" != "/" ]; then
     # run sed script (over arguments, or unmerged files if unspecified)
-    # TODO: figure out how to put args in a var to avoid duplication
-    if [ "$#" -gt 0 ]; then
-        sed -Esi -f "$DIR/_merge-sync-tags.sed" "$@"
-    else
-        git diff -z --name-only --diff-filter=U | xargs -0 sed -Esi -f "$DIR/_merge-sync-tags.sed"
-    fi
+    sed -Esi -f "$DIR/_merge-sync-tags.sed" "${files[@]}"
+
     # figure out how to fix up the sync tags
-    results="$("$KA_ROOT/tools/runlint.py" -l "$KA_ROOT/dev/linters/code_syncing_lint.py")"
+    lint="$("$KA_ROOT/tools/runlint.py" -l "$KA_ROOT/dev/linters/code_syncing_lint.py")"
     # actually fix them up
-    echo -n "$results" | sed -e 's/.*running: //' -e 's/ (dev.linters.*//' | sh -x
+    echo -n "$lint" | sed -e 's/.*running: //' -e 's/ (dev.linters.*//' | sh -x
 
     # check if that solved all our problems
-    bad="$(echo -n "$results" | grep -q "appears to be malformed")"
-    # TODO: also check for conflict markers!
-    if [ -z "$bad" ]; then
-        # we were able to resolve all conflicts
-        # print the diff, for the user's inspection
-        git diff
+    if echo -n "$lint" | grep -q "appears to be malformed" || grep -q '[<>|=]{7}'; then
+        echo "unable to resolve all conflicts :("
+        exit 1
+    fi
 
-        read -p "Look good [y]? " -n 1 -r
-        echo
+    # we were able to resolve all conflicts
+    # print the diff, for the user's inspection
+    git diff
 
-        if [[ $REPLY =~ ^[yY]*$ ]]; then
-            if [ "$#" -gt 0 ]; then
-                git add "$@"
-            else
-                git diff -z --name-only --diff-filter=U | xargs -0 git add
-            fi
-            exit 0
-        fi
+    read -p "Look good [y]? " -n 1 -r
+    echo
+
+    if [[ $REPLY =~ ^[yY]*$ ]]; then
+        git add "${files[@]}"
+        exit 0
     fi
 fi
 
